### ISSUE TITLE
Where is the code related to Optimization?

### ISSUE THREAD

**Issue by xiehuanyi** [RManLuo/reasoning-on-graphs#1]
Hi there, thanks for your job. But I have a little question. You mentioned that there are two kinds of optimization(Planning optimization & Retrieval-reasoning optimization.) in the process of generating relation paths in your paper. But I failed to find related code in the project. I just wonder how it is finetuned to make a llm able to generate reasonable relation paths. It's quite challenging because the llm may haven't seen many such tasks in the training process. Looking forward to your reply!

**Comment by RManLuo** [comment]
Hi Xiehuan,

Thanks for your interest in our work. We enable the LLM to generate valid relation paths through fine-tuning. 

We are preparing the code for the training stage right now. You can WATCH our repo; we will let you know when it is ready.

**Comment by RManLuo** [comment]
Code and data have been updated at fdc593901f2cd6056d73a1e8016557abe4d2f72e
