### ISSUE TITLE
Hits@1 Evaluation

### ISSUE THREAD

**Issue by cmavro** [RManLuo/reasoning-on-graphs#11]
Hi, great work!

I have a question about the Hits@1 evaluation. In file `evaluation results.py`, Hits is evaluated as follows:
```
def eval_hit(prediction, answer):
    for a in answer:
        if match(prediction, a):
            return 1
    return 0
hit = eval_hit(prediction_str, answer)
```
The result at Wepbqsp is: **86.36% (Hits)**

However, this snippet compares every answer with all $k$ generated predictions (Hits@k), and not the top-1 prediction. If I use the top-1 prediction only (similar to competing methods):
```
def eval_hit1(prediction, answer):
    for a in answer:
        if match(prediction[0], a):
            return 1
    return 0
hit = eval_hit1(prediction, answer)
```
The result at Webqsp drops: **80.34% (Hits@1)**

Is my understanding about the evaluation correct or am I missing something? Thank you!

**Comment by RManLuo** [comment]
Hi, Thanks for your interest in our work. Conventionally, the Hit@1 is evaluated by ranking the first prediction results generated by the model, which is not the first in the candidate answer. However, as the LLM cannot generate a ranking score of each answers, we treat all the answers predicted by the LLM as the first prediction. We check whether the ground-truth answer existed in the prediction to calculate Hit@1.
