### ISSUE TITLE
Out-of-Memory Issue

### ISSUE THREAD

**Issue by meaningful96** [RManLuo/reasoning-on-graphs#13]
Hi! I am reaching out regarding the current code implementation, which does not utilize DataParallel, making it unclear how to use multiple GPUs effectively. In your paper, you mentioned using two A100 GPUs, whereas in our case, we intend to use six A6000 GPUs. However, when we run the code as it is, it only utilizes two GPUs and encounters an Out-of-Memory issue.

Could you kindly provide guidance on how to configure the code to specify the number of GPUs to be used?

**Comment by RManLuo** [comment]
You can change the config here: https://github.com/RManLuo/reasoning-on-graphs/blob/418cd4bc066e8a37e07f360349a8feb0ff920229/config/deepspeed_zero3.yml#L15

You can find more details about distributed training here: https://huggingface.co/docs/accelerate/en/usage_guides/deepspeed

**Comment by meaningful96** [comment]
Thank you for helping me again!!
