### ISSUE TITLE
Is it possible to train the model on our own KGs?

### ISSUE THREAD

**Issue by jianghr-shanghaitech** [RManLuo/reasoning-on-graphs#16]
I have some knowledge graphs (KG) in the field of biology, stored in the form of triples, like ProteinKG25. Could I train and perform inference on this specific KG?

**Comment by RManLuo** [comment]
Yes. You can achieve this by preparing datasets following the format used in RoG and conducting planning optimization as well as retrieval-reasoning optimization.

**Comment by jianghr-shanghaitech** [comment]
Thank you very much for your prompt reply and excellent work! I will give it a try.
