### ISSUE TITLE
Question About the Necessity of ChatGPT in generate_explanation_results.py

### ISSUE THREAD

**Issue by wll-best** [RManLuo/reasoning-on-graphs#19]
Thank you for sharing your work and resources.
While running the command python src/joint_training/generate_explanation_results.py, I noticed that it seems to require the use of ChatGPT. However, as far as I understand from the paper, ChatGPT is not explicitly mentioned as part of the RoG framework or its training and inference process. Could you kindly clarify the following:

1. Is ChatGPT required to run the code?
2. If not mandatory, is there a way to bypass it?
3. Consistency with the paper: Is the use of ChatGPT in this step consistent with the methods described in the paper?

Your clarification would greatly help me understand and replicate your work. Thank you very much for your time and assistance!

**Comment by RManLuo** [comment]
Thank you for your interest. ChaGPT is used solely to generate explanation examples for injecting explainability into the RoG and can be replaced by any LLM, such as Llama-3-70B.
