### ISSUE TITLE
Can the Answer not in the extracted SubGraph?

### ISSUE THREAD

**Issue by MINJIK01** [RManLuo/reasoning-on-graphs#20]
Hello, I am a student who is studying Deep learning, thank you for your great work.

I just wonder about the coverage of the extracted graph (2-hop).
I checked the whole entities in the extracted subgraph and found that some answer entities are not in the graph.

Is this normal and can it happen?

In my view, if this happens the graph is not so useful to retrieve the path and llm should use their internal knowledge to answer the question.

Thank you.

**Comment by RManLuo** [comment]
Hi, Thanks for raising this interesting question. It is possible that answers do not exist in KGs. Thus, it is a good idea to combine the internal knowledge of LLMs with KGs to enable better reasoning.

**Comment by MINJIK01** [comment]
Thank you for answering! :)
