### ISSUE TITLE
Knowledge graph

### ISSUE THREAD

**Issue by jw9603** [RManLuo/reasoning-on-graphs#7]
Hi there, thanks for your job.
But I have a little question. You mentioned that there are two kinds of optimization(Planning optimization & Retrieval-reasoning optimization.) in the process of generating relation paths in your paper.

In planning optimization, you aim to distill the knowledge from KGs into LLMs to generate relation paths as plans.

Does creating a relation path through prompting in LLM, instead of actually using a knowledge graph, carry the same meaning as using a knowledge graph?
But, in the code, it seems like 'subgraph' is used in conjunction with 'prompt'....

Thank you.

**Comment by RManLuo** [comment]
Thanks for your interest in our work and bringing up this inspiring question. From my perspective, prompting the LLMs with the relation path is "theatrically" identical to distilling the knowledge from KGs into LLMs via fine-tuning. However, in practice, it could be quite challenging due to the enormous number of relations in KGs.

In the planning module, we only generate the relation path as plans that do not contain any factual knowledge.  But in the retrieval-reasoning module, we use the relation path to retrieve reasoning paths from KGs, which are used to finally conduct reasoning. Thus, we cannot say the relation paths are equivalent to KGs.

**Comment by jw9603** [comment]
But aren't you using the Freebase knowledge graph?

**Comment by RManLuo** [comment]
> But aren't you using the Freebase knowledge graph?

Yes, we use the Freebase in experiments.

**Comment by jw9603** [comment]
But didn't you mention in your response that you're not directly using the knowledge graph but rather generating relations through prompts, and that this is considered equivalent to using the knowledge graph?

**Comment by RManLuo** [comment]
> But didn't you mention in your response that you're not directly using the knowledge graph but rather generating relations through prompts, and that this is considered equivalent to using the knowledge graph?

In our work, we do not prompt the llms with the relation path from kgs. We distill the knowledge from kgs via planing-optimization (more details in our paper). But, I also agree with the possibility of using prompt. I hope this can address the miss-understanding in previous response.

**Comment by jw9603** [comment]
In the "planning optimization" process, you are correct that they do not explicitly mention the use of a Knowledge Graph (KG), and it appears that they feed the planning prompt to the Large Language Model (LLM) to output valid relations without utilizing a KG. However, in equation (4), the part under the sigma (∑) symbol, where z belongs to Q(z|a,q,G), does indeed refer to G as the Knowledge Graph (KG)?

If this is correct, the part where they incorporate the KG into the planning prompt is not explicitly mentioned in the paper. They seem to focus on using the language model to infer knowledge from text-based sources and find relations without directly incorporating a KG into the planning prompt.

I'm sorry for bothering you with continuous questions.

Thank You.


**+) May I read the paper again more closely and try to answer my own question?**

**My Answer and question:**

I understand it this way: Conceptually, question and answer entities are extracted from the knowledge graph, and the relation paths are considered as ground_paths. (https://github.com/RManLuo/reasoning-on-graphs/blob/master/src/qa_prediction/gen_rule_path.py#L174)

There are also relation paths generated based on prompts (up to equation 3). 

Then, the optimal relation paths (plans) are determined based on both the generated relation paths and the ground_paths, as described in equation (8). 

If this is correct, could you tell me where the code for executing equation (8) is?

**Comment by Halhawasi** [comment]
What is the way or metric you used to evaluate the right or wrong answer or similarity between the answer to the question from the QA dataset and the answer from your model? How do you know that you get the right answer? Are you using EM or F! or something else?
