### ISSUE TITLE
Transfer to other KG

### ISSUE THREAD

**Issue by xuzhaoyang-svg** [RManLuo/reasoning-on-graphs#8]
Hi there，thanks your work! I would like to know how to transfer your model to a knowledge graph in my field and create a knowledge graph based LLM question answering system.

**Comment by RManLuo** [comment]
Hi, thanks for your interest in our work. You can follow the details of training presented in the README file. For preparing datasets for different KGs, you can refer to the code [here](https://github.com/RichardHGL/WSDM2021_NSM/tree/main/preprocessing/Freebase).

**Comment by xuzhaoyang-svg** [comment]
Thank You.

**Comment by happyrenxiaozhao** [comment]
@xuzhaoyang-svg hi,did you successfully transfer to another KG? can you give me an E-mail address? It may facilitate our communication. I am looking forward to your reply.
